package Assets;

public enum tileType {
	DEFAULT, RCASTLE, BCASTLE, BR_LWALL, BL_LWALL, TR_LWALL, TL_LWALL, RIGHT_VERTICAL_WALL, LEFT_VERTICAL_WALL,
	HORIZONTAL_WALL,

//	LWALL, IWALL, HEART,

//	VERTICAL_IN_WALL, VERTICAL_OUT_WALL, HORIZONTAL_WALL, BR_LWALL,
}

//public enum LWallTypes {
//	BR, BL, TR, TL
//}

//public enum IWallTypes {
//	IN, OUT
//}
